### ISSUE TITLE
Prior art

### ISSUE THREAD

**Issue by larsbrinkhoff** [Alhadis/Harvester#1]
You may be able to get some ideas from http://github.com/larsbrinkhoff/github-scripts, in particular `samples.sh`.

**Comment by Alhadis** [comment]
Haha, thanks mate. ;)

Does it still work for you? I mean, with the issue with search results I pointed out...

**Comment by larsbrinkhoff** [comment]
No, I get the same result. :-(

**Comment by Alhadis** [comment]
Shit, that's the precise opposite of what I wanted to hear. :(

Grrreeeeaaat, this is gonna complicate things. -_- I wonder if @arfon can have a word to his peers about getting this fixed. 'Cause it's not gonna make surveying extension usage on GitHub any fun...

**Comment by arfon** [comment]
> No, I get the same result. :-(

What's not working sorry?

**Comment by Alhadis** [comment]
Running searches for filename extensions if you're not signed in. :\ Try [opening this](https://github.com/search?q=extension%3Apic+NOT+nothack&type=Code) in an incognito window, then open it while you're logged in.

**Comment by Alhadis** [comment]
I was looking forward to harvesting and generating reports on filename/extension usage on GitHub... suddenly, this happens, heh.

**Comment by arfon** [comment]
> Running searches for filename extensions if you're not signed in. :\ Try opening this in an incognito window, then open it while you're logged in.

Hrm, I wonder why we stopped that from working. I'll see what I can find out.

**Comment by larsbrinkhoff** [comment]
@arfon Any news on this?  It does make it harder to research code on GitHub.

**Comment by Alhadis** [comment]
Guys, I dunno how much longer this is gonna be an issue for, so I've [rewritten the URL scraper in JavaScript](https://github.com/Alhadis/Harvester/blob/js/harvester.js) to run in a browser console.

**Usage:**  
```js
harvest("extension:pic").then(_=> new Notification("Done"));
```

Then when a desktop notification appears to tell you it's finished, run this:

```js
copy(silo.reap("extension:pic")); // Copies URL list to clipboard
```

I've throttled the script to send one request per second, because GitHub [barked at me](https://github.com/429) after loading too many pages too quickly. And, of course, the script has to be run from a GitHub.com-hosted page due to CORS issues.

@larsbrinkhoff, @pchaigno, have fun. @arfon, I hope this gets looked at sooner or later...

**Comment by pchaigno** [comment]
> Hrm, I wonder why we stopped that from working. I'll see what I can find out.

@arfon Because it was an easy target for L7 DDoS attacks maybe?
