### ISSUE TITLE
Notification permission deprecation in Firefox

### ISSUE THREAD

**Issue by pchaigno** [Alhadis/Harvester#14]
Just a heads up: I'm getting the following warning with Firefox 71.0 when I paste the script:

> Requesting Notification permission outside a short running user-generated event handler is deprecated and will not be supported in the future.

**Comment by Alhadis** [comment]
\*sigh\* I could place an element on the page with a button that says *"Enable notifications"*, but honestly, I think it's high-time I rewrote this as a proper command-line app (utilising the GitHub API that is ostensibly capable of performing site-wide file-extension searches).

I'm not resorting to a [`window.alert`](http://mdn.io/window.alert) for this, BTW, because it steals focus and is overall considered atrocious practice amongst web developers. That is, however, an easy cop-out solution.
