### ISSUE TITLE
Hitting rate limit...

### ISSUE THREAD

**Issue by melund** [Alhadis/Harvester#16]
When trying to run haverster I get a rate limit error. Even if I follow the steps on the page.

```
   Whoa there!
      You have triggered an abuse detection mechanism.
        Please wait a few minutes before you try again;
        in some cases this may take up to an hour.
        
        Contact Support —
        GitHub Status —
        @githubstatus
```

Is there anyway around this, or other ways to judge the usage of certain file types before submitting to linguist?

**Comment by Alhadis** [comment]
👋  Hey mate,

🤔 I'm unable to reproduce this error, which is puzzling. Are you running multiple harvests simultaneously?

If not, try raising [the delay](https://github.com/Alhadis/Harvester/blob/b2c6edd1bf530583e64cf586babae8204b5dcc0d/harvester.js#L141-L143) from 2000 milliseconds to something higher. I hardcoded it because I didn't foresee a scenario where it'd need to be set on a case-by-case basis…

**Comment by Nixinova** [comment]
Also ran into the rate limiter

![image](https://user-images.githubusercontent.com/42429413/125353642-e9bd9180-e3b6-11eb-840c-9dc92232b70f.png)

![image](https://user-images.githubusercontent.com/42429413/125353582-d8748500-e3b6-11eb-8701-d6a628309386.png)

**Comment by Alhadis** [comment]
I think it's time I started work on #15… This is ridiculous.

I'll try to allocate time for this once my hands are free.
