### ISSUE TITLE
SyntaxError: Expected at least one entry to match `.code-list-item`

### ISSUE THREAD

**Issue by palfrey** [Alhadis/Harvester#17]
While looking at https://github.com/search?q=extension%3Ajanet+NOT+nothack&type=Code
![Screenshot 2021-10-08 at 18 08 45](https://user-images.githubusercontent.com/38532/136596155-ab89dc6b-e450-4b0c-9b84-33ec43cb17f8.png)

**Comment by palfrey** [comment]
This was with running `await harvest()` but `await harvest("extension:janet", "NOT nothack")` was looking more fruitful but then I hit https://github.com/Alhadis/Harvester/issues/16#issuecomment-878584226

**Comment by Alhadis** [comment]
This is happening because GitHub's servers are responding with an empty search-result page, indicating that its abuse detection mechanism has been triggered. Exactly what triggers this is a mystery to me—until recently, it was purely a matter of request rates (hence the throttled loading).

I know it's frustrating, but there's nothing I can do short of rewrite this crappy script to use GitHub's APIs like users are _supposed_ to (see #15). It's high on my to-do list, but lately I've had limited time to spend on coding. Sorry. 😞 Don't think I've forgotten or overlooked this issue, though.

**Comment by lpil** [comment]
I've written a script that does as you've suggested there and I've also started to have these problems in the last few months. Sometimes the API will just say there's no more results, even when I know there it and am querying far below the rate limit. I'm not sure it's possible to count repos for a language any more using this API.
