### ISSUE TITLE
SyntaxError: Unable to extract total number of results from header

### ISSUE THREAD

**Issue by andrewrk** [Alhadis/Harvester#6]
I followed the instructions from the README and get this in the console:

```
SyntaxError
​
columnNumber: 20
​
fileName: "harvester.js"
​
lineNumber: 222
​
message: "Unable to extract total number of results from header"
​
stack: "die@debugger eval code:222:20\nnext@debugger eval code:164:11\n"
​
title: "Unexpected Markup Error"
​
__proto__: Object { stack: "", … }
debugger eval code:80:4
Object { lastPageSnapshot: DocumentFragment […] }
```

**Comment by Alhadis** [comment]
Do you still have the page open in your browser tabs?

**Comment by Alhadis** [comment]
Scratch that, I'm getting it too. It's happening because GitHub changed their code... *again*. 

~~~html
<div class="d-flex flex-column flex-md-row flex-justify-between border-bottom pb-3 position-relative">
    <h3>    112,332 code results </h3>
~~~

I'm afraid this is to be expected... I'll amend a fix and hope it'll take a while for them to change their minds again. 😞

**Comment by Alhadis** [comment]
Alright, try again now. =) Please yell out if you encounter any other issues, okay? Thanks!

**Comment by andrewrk** [comment]
Thanks, I can confirm it worked for me. If only GitHub would stabilize an actual API for this kind of search eh?

**Comment by Alhadis** [comment]
HAHAHAHAH! Oh man, you're tellin' me. 😅 I'm still holdin' out for the day GitHub add proper search functionality for this, because the song-and-dance routine of scraping data from AJAX-loaded search-result pages and waiting for the parsers to break at the next minor markup change... yeah, that's reeeeeeeeeally gotta stop. :(

**Comment by andrewrk** [comment]
Especially since it's part of the process of getting linguist PRs merged.

**Comment by Alhadis** [comment]
Heh, exactly.

A couple of years ago, Linguist contributors already had tools to perform automated searching and downloading of files to gauge in-the-wild usage of new formats (as well as locating any potential naming conflicts). I was halfway through writing one of my own (in Perl) when GitHub changed the rules of their search engine, limiting it to logged-in members only.

This, of course, broke everybody's tools we were using or working on, and this harvester script was the eventual outcome. 😥 It's less than ideal, but it's the best I can do without risk of jeopardising user accounts...
