### ISSUE TITLE
Harvester needs better recovery from unexpected blank pages

### ISSUE THREAD

**Issue by Alhadis** [Alhadis/Harvester#8]
@pchaigno This has been affecting a lot of URL harvests lately, I don't know if you've noticed or this is an Aussie internet thing. 😀

<img src="https://user-images.githubusercontent.com/2346707/44802351-d47ffa80-abfe-11e8-928c-45630a653882.gif" alt="Figure 1" />

**Comment by pchaigno** [comment]
Never had that issue :/
Neither with Harvester nor during my own browsing.

**Comment by Alhadis** [comment]
Well it's been a real pain-in-the-arse the last couple days. I'll see what happens if I change the randomly generated keycode to another one and then refresh the botched page...

**Comment by pchaigno** [comment]
Have you tried reporting it to GitHub support?

**Comment by Alhadis** [comment]
No I haven't. 😅 Should I?

BTW, you'd probably get it too if you ran a search for the `.flf` file extension. It seems to be affecting this particularly bad.

**Comment by Alhadis** [comment]
Okay, weird. 🤔 It works okay if I load the *next* page, and then go back to the previous one, and it suddenly works as expected. :D

Yeah, maybe I should submit this shit to GItHub report. Doesn't seem normal.

**Comment by pchaigno** [comment]
> Should I?

Well, it's very rare to have free support for a website and they answer very fast (< 48h), so I tend to use it.

Usually I get one of three answer:

1. I missed something and I feel dumb.
0. There's a bug and they quickly fix it.
0. There's a bug and, after the initial answer, I never hear from them again and the bug is never fixed.

To be honest, case 2 is pretty rare and case 1 happens increasingly often to me (that's why I push other people to report now :-) )... But it still feels worth it because you get a quick answer.

**Comment by Alhadis** [comment]
Haha, mate.... :') Given we're already skirting the line of what's appropriate site behaviour by downloading stuff automatically (**BUT NOT *TOO* FAST!**), I'd say their support team would make my report pretty low-level.

Heck, I could even get in *trouble* for all I know. 🤣
